In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import roc_auc_score

In [2]:
df = pd.read_csv(r"C:\Users\Trilokesh\Downloads\Downloads\Datas\MJP_DATA.csv")

In [3]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4      5.0  
1      9.8      5.0  
2      9.8      5.0  
3      9.8      6.0  
4      9.4      5.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1598 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1598 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1598 non-null   float64
dtypes: float64(12)
memory usage: 150.0 KB


In [5]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1598.000000  1599.000000   
mean      0.087467            15.874922             46.433041     0.996747   
std       0.047065            10.460157             32.876249     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1598.000000  1599.000000  1599.000000  1598.000000  
mean      3.498586     0.658149    10.422983     5.636421  
std       0.080346     0.169507     1.065668     0.807665  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.520000     0.550000     9.500000     5.000000  
50%       3.520000     0.620000    10.200000     6.000000  
75%       3.520000     0.730000    11.100000     6.000000  
max       3.900000     2.000000    14.900000     8.000000

In [6]:
df.isnull().any()

fixed acidity           False
volatile acidity        False
citric acid             False
residual sugar          False
chlorides               False
free sulfur dioxide     False
total sulfur dioxide     True
density                 False
pH                       True
sulphates               False
alcohol                 False
quality                  True
dtype: bool

In [7]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    1
density                 0
pH                      1
sulphates               0
alcohol                 0
quality                 1
dtype: int64

In [8]:
df['total sulfur dioxide'].fillna(df['total sulfur dioxide'].mode()[0],inplace=True)
df['pH'].fillna(df['pH'].mode()[0],inplace=True)
df['quality'].fillna(df['quality'].mode()[0],inplace=True)

In [9]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [10]:
x=df.drop(columns=['fixed acidity', 'residual sugar']).values 
x

array([[ 0.7  ,  0.   ,  0.076, ...,  0.56 ,  9.4  ,  5.   ],
       [ 0.88 ,  0.   ,  0.098, ...,  0.68 ,  9.8  ,  5.   ],
       [ 0.76 ,  0.04 ,  0.092, ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 0.51 ,  0.13 ,  0.076, ...,  0.75 , 11.   ,  6.   ],
       [ 0.645,  0.12 ,  0.075, ...,  0.71 , 10.2  ,  5.   ],
       [ 0.31 ,  0.47 ,  0.067, ...,  0.66 , 11.   ,  6.   ]])

In [11]:
x.shape

(1599, 10)

In [13]:
y=df['quality'].values
y

array([5., 5., 5., ..., 6., 5., 6.])

In [14]:
y.shape

(1599,)

In [15]:
from sklearn.preprocessing import OneHotEncoder 
one=OneHotEncoder() 
z=one.fit_transform(x[:,1:4]).toarray() 
z

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [26]:
x_train.shape

(1279, 11)

In [27]:
x_test.shape

(320, 11)

In [28]:
y_train.shape

(1279,)

In [29]:
y_test.shape

(320,)

In [30]:
y=df['quality']>5
y

0       False
1       False
2       False
3        True
4       False
        ...  
1594    False
1595     True
1596     True
1597    False
1598     True
Name: quality, Length: 1599, dtype: bool

In [32]:
x=df.iloc[:,:-1] 
x

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.52       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.52       0.75   
1597                 32.0                  44.0  0.99547  3.52       0.71   
1598                 18.0                  42.0  0.99549  3.52       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0  

[1599 rows x 11 columns]

In [34]:
from sklearn.preprocessing import StandardScaler 
sc=StandardScaler() 
sc_x_train=sc.fit_transform(x_train) 
sc_x_train

array([[ 0.90103398,  0.05480282,  0.9094138 , ...,  0.27176305,
        -0.22358408, -0.95579434],
       [ 1.41998736, -1.47967601,  0.9094138 , ...,  0.27176305,
        -0.68130963, -0.76727388],
       [ 0.90103398, -0.98645067,  1.4208416 , ...,  0.27176305,
         0.74908272,  0.17532846],
       ...,
       [-0.25219574,  0.21921126,  0.19341488, ...,  0.27176305,
         0.17692578, -0.86153411],
       [ 2.68854005, -0.32881689,  1.11398492, ...,  0.27176305,
         0.11971008,  2.15479335],
       [ 0.84337249,  2.46612668,  0.24455766, ...,  0.27176305,
        -1.0246038 , -0.95579434]])

In [35]:
sc_x_test=sc.fit_transform(x_test) 
sc_x_test

array([[ 1.44653617, -0.29922497,  0.8557103 , ...,  0.24478167,
         0.72205872,  0.31519731],
       [-0.08433993,  1.83333604, -1.39006001, ...,  0.24478167,
        -0.85116573, -0.79369656],
       [ 0.48265122, -1.39597062,  0.33343814, ...,  0.24478167,
         1.26926723,  1.14686771],
       ...,
       [ 0.48265122, -1.09131905,  0.80348308, ...,  0.24478167,
        -0.7143636 ,  0.86964424],
       [ 0.48265122,  1.49821931, -1.18115114, ...,  0.24478167,
        -0.78276467, -0.70128874],
       [-0.02764082, -1.21317968,  0.80348308, ...,  0.24478167,
        -0.7143636 ,  1.70131464]])

In [36]:
from sklearn.svm import SVC
model=SVC() 
svm=SVC() 
svm.fit(x_train,y_train)

SVC()

In [37]:
y_pred=svm.predict(x_train)

In [40]:
from sklearn.svm import SVC
svc=SVC(kernel='linear',C=5) 
svc.fit(x_train,y_train)

SVC(C=5, kernel='linear')

In [42]:
from sklearn.metrics import accuracy_score 
print(accuracy_score(y_train,y_pred))

0.5027365129007036
